
# perform HDL-L analysis for all 100 replicates for a given block and condition, and for a specific reference data set

# arguments:
# - [1] reference data set
# - [2] condition label
# - [3] block ID

# input files:
# - LD reference files, preprocessed into HDL-L format (preprocessing based on the exact SNPs used for each block)
#   - ukb_main: from same data as used in generate.r, N = 167636
#   - ukb_503 / ukb_1K / ukb_5K / ukb_10K / ukb_100K: from UK Biobank subsamples of different sizes; do not overlap with ukb_main
#   - g1000: from European panel of the 1,000 Genomes data
#   - orig: original HDL-L LD files, downloaded from https://zenodo.org/records/14825987
# - .info and .stats1/2 files created by generate.r script

# output files:
# - .res file with analysis results


flags = commandArgs(T)

library(HDL)

reference = flags[1]
condition = flags[2]
block = as.numeric(flags[3])


ref.sizes = list(orig = 335272, ukb_main = 167636, ukb_100K = 100000, ukb_10K = 10000, ukb_5K = 5000, ukb_1K = 1000, ukb_503 = 503, g1000 = 503)
if (is.null(ref.sizes[[reference]])) stop("no sample size provided")


root = "[ROOT DIRECTORY]"

input.dir = paste0(root, "/generate/output/", condition, "/block", block)  # contains the files generated by the generate.r script, for the given block and condition
analysis.dir = paste0(root, "/analyse/hdl")


# preprocessed LD reference data 
if (reference == "orig") { #NB: must have closing '/'	
	ld.path = paste0(analysis.dir, "/reference/orig/LD.path/")  
	bim.path = paste0(analysis.dir, "/reference/orig/bimfiles/")  
} else ld.path = bim.path = paste0(analysis.dir, "/reference/output/", reference, "/")  



output.dir = paste0(root, "/analyse/hdl/output/", reference, "/", condition)

dir.create(output.dir, showWarnings=F, recursive=T)



# load simulated summary statistics
snp.info.file = paste0(input.dir, "/", condition, "_block", block, ".info")
snp.stats.files = paste0(input.dir, "/", condition, "_block", block, ".stats", 1:2)

snp.info = read.table(snp.info.file, header=T, stringsAsFactors=F)
snp.stats = lapply(snp.stats.files, read.table, header=T, stringsAsFactors=F)
no.iter = ncol(snp.stats[[1]])



results = NULL
for (iter in 1:no.iter) {
	# create data frames with summary stats for current replicate
	stats = list()
	for (p in 1:2) stats[[p]] = cbind(snp.info, Z=snp.stats[[p]][,iter])

	# run analysis
	res = HDL.L(stats[[1]], stats[[2]], "pheno1", "pheno2", LD.path = ld.path, bim.path = bim.path, chr = 22, piece = block, N0 = 0, Nref = ref.sizes[[reference]])
	results = rbind(results, res)
}

# save output
output.file = paste0(output.dir, "/", reference, "_", condition, "_block", block, ".res")
write.table(results, file=output.file, row.names=F, quote=F, sep="\t")











